### ISSUE TITLE
Stuck on Apple logo on first boot

### ISSUE THREAD

**Issue by rodrigozago** [Nihhaar/Hackintosh-Dell-7567#11]
Hello, I'm new to hackintosh 
I tried to do and get stucked on a Backtrace Crash. 
This message is shown to me:
Attempting System restart...MACH Reboot. 
If someone could point the directory to the solution...
Thanks.

**Comment by rodrigozago** [comment]
I used the -v flag to see the issue.

**Comment by Nihhaar** [comment]
Can you post the image of the error?
Also need more details like OS version, which release are you using...

**Comment by Nihhaar** [comment]
Closing issue because I am archiving this repo.
