### ISSUE TITLE
Can boot into mac by clover

### ISSUE THREAD

**Issue by hhoangna** [Nihhaar/Hackintosh-Dell-7567#14]
Every thing OK until i restart. I can't boot into mac and it has loop reboot on logo.  When a pressed space at my mac volume I realized that options for boot have null value.  Then,  I try to boot by USB and it run normally.  How should I do to boot by clover without USB?

**Comment by Nihhaar** [comment]
Did you install clover on your Mac volume and copied kexts from my files for post install? See readme

**Comment by hhoangna** [comment]
Yes. I did. Please see this clip below
https://share.icloud.com/photos/0qm7sfol09q3WaPWOvR9Ky-Mw
Arrcoding video, i realized when i boot into clover the options for boot have null value and boot by usb the options have available value

**Comment by Nihhaar** [comment]
Your kernel panic caused by VoodooGPIO from the video.
* Are you using VoodooI2Cfrom my release? or use the latest one from official voodooi2c repo
* Did you update config.plist for post install files? This includes patches for GPIO pinning
* Did you copy DSDT, SSDT from `patched` folder? These also include patch for GPIO pinning

**Comment by hhoangna** [comment]
Am using kexts form your repo. 
Aslo copied DSDT, SSDT from your patched folder to my EFI partition/EFI/Clover/APCI...
You said "update config.list". It mean replace config.list in my EFI by your config.list in repo, right?
I did every steps in readme

**Comment by Nihhaar** [comment]
Yeah replace config.plist. Not sure why you are getting panic. You can try pinning manually yourself from here:
https://voodooi2c.github.io
Or
Use Voodoops2 instead of voodooi2c

**Comment by hhoangna** [comment]
You can see null value in option for boot? Maybe I forgot set default volume. But i didn't see step set boot volume! Is it necessary?

**Comment by Nihhaar** [comment]
Boot options are null only. Not necessary.

**Comment by hhoangna** [comment]
Yup! Boot option null when boot from volume that i have installed mac. However boot from USB, boot options not null.

**Comment by Nihhaar** [comment]
Boot options are null because Whatevergreen kext takes care of disabling GFX firmware, where as in usb booting, the kext is not there hence the boot options are needed.

Can you tell the os version? Also try installing latest kext from Voodooi2c repo.

**Comment by hhoangna** [comment]
You mean bios version?

**Comment by Nihhaar** [comment]
No, macos version. Mojave or High Sierra?

**Comment by hhoangna** [comment]
Mojave 10.14

**Comment by hhoangna** [comment]
Could you support for me via Teamviewer?

**Comment by hhoangna** [comment]
it seems, my issue like #12 
Did it resolve?

**Comment by AnharmA** [comment]
Yeah, I have same issues booting it with Nihhaar's Clover release, but actually using -f command on boot and got same result.

Nihhaar, are you updating your laptop from HS? Maybe if you install from scratch you could get same result. Or maybe matching Clover version that actually worked

**Comment by hhoangna** [comment]
@AnharmA Do your audio work? My don't work

**Comment by hhoangna** [comment]
@Nihhaar Hey guy, I make sure the problem because your files in APCI. You should review, pls

**Comment by Nihhaar** [comment]
Updated ACPI files, be sure to check it out
