### ISSUE TITLE
Can't boot and no camera 

### ISSUE THREAD

**Issue by lersy** [Nihhaar/Hackintosh-Dell-7567#15]
First of all, thanks for providing these needed kexts, patches in a single .zip file.
I have a Dell 7577 but I gave a go to your tutorial. I did post installation steps as others but having the same problem. Can't boot into MacOS. I think it is an issue with that trackpad thing. Eventhough I updated both of kexts from GitHub repository, it didn't change the situation. I can boot with installation usb anyway and it is ok for now. Will you have a work around for this anytime soon?

And I can't use my pc camera. In high Sierra, my smbios was something like MacBook Air 6,2 and camera was fine. Do you think is it related something to it? Is there anyone else having this problem or is it just me because mine is a 7577.

Sorry for my English I will be glad if you look into this. Thanks in advance.

**Comment by Nihhaar** [comment]
Hi,
Try the following:
* Remove DSDT.aml, SSDT-I2C.aml from your patched folder
* Remove VoodooI2C.kext, VoodooI2CHID.kext from Clover/Other Kexts
* Replace your the config.plist with the attached one here:
[config.plist.zip](https://github.com/Nihhaar/Hackintosh-Dell-7567/files/2528865/config.plist.zip)

Not sure for camera, try this first and tell me the result.

**Comment by lersy** [comment]
Hi,
I did as you wrote and it booted directly. I can't use my camera. It is very important for me because I use FaceTime so much. Does your webcam work? Could you lead me to fix this problem?
Thanks so much again for your effort.

**Comment by Nihhaar** [comment]
Hi,
Camera is working fine (since mine is 7567)

Yours will need a custom SSDT-UIAC different from mine for injecting USB ports for 7577.
I really can't help here but either you have to follow this guide and prepare your own or see if anyone already did this.
https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/

**Comment by Nihhaar** [comment]
Since you are here, try this:
* Remove SSDT-UIAC.aml from patched folder and replace it with the attached one
[SSDT-UIAC.aml.zip](https://github.com/Nihhaar/Hackintosh-Dell-7567/files/2531421/SSDT-UIAC.aml.zip)

**Comment by lersy** [comment]
I removed and copy the one you provided but it still says there is no connected camera both in Photoboth and FaceTime 
I can follow the guide but it can mess up things for me since I am not good at that stuff. Is this something related to dsdt patches? 

Here is a copy of my patched ACPI folder which I use with High Sierra. I didn't patch it , I found on internet but I don't remember exactly on which page now. I can use webcam with these ones but I am not sure what to do. Can you help me ?

It is smooth really now, better than high Sierra. I don't want to lose purity as much as possible. Thanks to you it feels ok now.

https://drive.google.com/open?id=15MW3J9bLZnwLqzlMJFfm_seq7sCTPlOy

I wish you are around and see this post

**Comment by Nihhaar** [comment]
* Remove SSDT-UIAC.aml and add DSDT.aml you attached in the drive to patched folder and check.

**Comment by lersy** [comment]
Nihhaar, 
I removed SSDT-UIAC.aml and add DSDT.aml I have but the result is same. It still says there is no connected camera. 

May I ask another question? In previous build I have only 4 patches in my folder. But you provided much more. Why did you do that? Did you patch them separately? Is this a safe way to patch? I am not sure of course but I thought that my patches were combined so there are less .aml files.

I should find a way to patch this on my own but thanks for others. If you can help me it means a lot while I am trying to figure it out.

**Comment by lersy** [comment]
With my DSDT.aml brightness function started working. I should definitely patch my system entirely. How can I check which part is working which part is not? Is there a list for it?

**Comment by Nihhaar** [comment]
SSDT-256.aml -> SSDT for Audio (your sound card- Realtek ALC 256)
SSDT-Nvidia-Disable.aml -> Disablling nvidia card
SSDT-PNLF.aml -> For brightness

All these SSDTs and the DSDT is compiled into a single binary finally. SSDTs are like add-ons to DSDT: they finally merge anyway. Patching DSDT can be done in two ways:
1) Patching DSDT directly and including it in the patched folder (called injection of DSDT).
2) Add these "patches" as SSDTs so that at runtime, clover loads DSDT from your system firmware and merges it with these SSDTs.

Not about safest way to patch but (2) is cleaner since each SSDT has a purpose of its own. Also, when you update your BIOS, DSDT may be changed by your vendor: so you have to patch again if your are using (1). Using (2),  we need not worry about updates.

Read more here (a very good and recommended read):
https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/

**Comment by Nihhaar** [comment]
Yes, you can't expect everything working with files from a different laptop. Not a detailed list, but here are some:
* Audio
* Backlight
* USB Injection (Includes camera)
* Disabling Discrete GPU
* PS2Controller: keyboard and mouse
* Native Power Management

If you are interested in learning, read all the pinned guides from here:
https://www.tonymacx86.com/forums/high-sierra-laptop-support.192/

starting from FAQ and "Booting the OS X installer on LAPTOPS with Clover".

**Comment by lersy** [comment]
Thanks for replying. This gives me an opinion to find my way.
I will read guides you shared as soon as possible in near future. Now it works nearly thanks to you.
I am sorry if I am violated rules here as I use it like a forum. 
Have a good day.

**Comment by Nihhaar** [comment]
No problem.
If you are interested, I can give files for *probably* working camera but it is just a hack. Also, you have to use the SSDT-Nvidia-Disable.aml instead of my SSDT-DGPU.aml for properly disabling nvidia card. This leads to significant battery life.

**Comment by lersy** [comment]
I turned off my pc but if you give me files I can try them tomorrow. 
I noticed battery drains so fast. What is the difference between mine and yours? Doesn’t your pc have a Nvidia 1050ti dgpu?

**Comment by Nihhaar** [comment]
Yes, same GPU but internal connection of the GPU to motherboard is different.

**Comment by lersy** [comment]
Nihhaar,
will you provide me files you mentioned? Anyway here is a folder which contains my original and patched ACPI and an AIDA64 report which was taken by windows 10 operating system.
Maybe you can check it if you have a free time and tell me what to do.
[ACPI.zip](https://github.com/Nihhaar/Hackintosh-Dell-7567/files/2534091/ACPI.zip)

**Comment by Nihhaar** [comment]
Hi,
* Replace SSDT-Disable_DGPU.aml with your High Sierra's "SSDT-Nvidia-Disable.aml"
* Remove SSDT-UIAC.aml from patched folder (if it is there)
* Update config.plist with the attached one
[config.plist.zip](https://github.com/Nihhaar/Hackintosh-Dell-7567/files/2536224/config.plist.zip)

**Comment by lersy** [comment]
Hey Nihhaar,
* Replaced SSDT_Disable_DGPU.aml with mine previous one.
* There is no SSDT-UIAC.aml in patched folder and I removed VoodooI2C.kext, and VoodooI2CHID.kext from Clover/kexts/other
* Replaced with latest config.plist but I still can't access to my usb 3 ports. However usb2 port has worked since I installed Mojave. 

Thanks for your effort so far. I wish there is someone who has usb function working with 7577.

**Comment by lersy** [comment]
Hey there, 

I nearly built my hackintosh. I appreciate your efforts. I know this page is not a forum but you are one of the friendliest one in the community. I don’t open another issue page because my pc is not 7567. Yet I would like to ask you a question about trackpads.

First of all, if I use your ssdt-iac.aml along with other kexts related to trackpad , when I boot up my pc, I can’t use my trackpad.

As far as I have learned so far, there are trackpad manufacturers which are synaptics, elan or als. My question is ;
- How could you identify your trackpad model? I can boot into windows 10 and mac os mojave.

- Can you use gestures with your trackpad like 3 fingers or 4 fingers things? Right now I can use, tap to click with two fingers to click and scrooling with two fingers. I only use voodoops2.kext now

If you provide me knowledge about trackpad I would be glad. 

Thanks for everything you have done so far. When I figure out everything I will have suggestions for you also to update your guide but can’t be sure because models are different

**Comment by Nihhaar** [comment]
Sorry for the late response (little busy),
You can start from here:
* https://voodooi2c.github.io/#Installation/Installation
* https://voodooi2c.github.io/#GPIO%20Pinning/GPIO%20Pinning

Trackpad model can be found from device manager in windows, something like this:
![elan](https://user-images.githubusercontent.com/20909963/49238284-1733b780-f426-11e8-84de-d8454cd34591.JPG)
For I2C (precision touchpads), it would be shown as I2C-HID device.
Yes, 3 & 4 finger gestures work (little buggy but works ;))

**Comment by Nihhaar** [comment]
Closing issue because I am archiving this repo.
