### ISSUE TITLE
7567 1050Ti with Intel Core i5 7300 boot issue

### ISSUE THREAD

**Issue by laloalire** [Nihhaar/Hackintosh-Dell-7567#16]
in this laptop seems like i just can't reach the installer screen, what could be? is almost the same Dell model as you, but with an i5 7300 Kaby Lake
please help!

**Comment by Nihhaar** [comment]
No one faced this problem upto now. Did you try with USB 2.0?

**Comment by laloalire** [comment]
you mean with a 2.0 usb? or a 2.0 usb port? because i don't think this laptop has a 2.0 usb port

**Comment by Nihhaar** [comment]
2.0 usb

**Comment by Nihhaar** [comment]
What's the exact error you are getting? Try booting it verbose and take a
photo.

**Comment by laloalire** [comment]
![fail1](https://user-images.githubusercontent.com/18712668/48074078-5e1eec00-e19d-11e8-97fe-5eca852131c9.jpg)
This is the last verbose message before a kernel panic, and i will try with a 2.0 usb and see if got success (the 3.0 usb worked in another sony vaio laptop) but no in this one

**Comment by Nihhaar** [comment]
It's not a panic. Try 2.0. it will work

**Comment by laloalire** [comment]
now i got this message (not the same)
could be caused by my second SATA HDD?
i have both, m.2 256gb SSD and 750gb SATA HDD
![fail3](https://user-images.githubusercontent.com/18712668/48080848-e3a99880-e1ab-11e8-8693-f507ab4b97f6.jpg)

**Comment by Nihhaar** [comment]
Why are you getting HDD error while booting from usb? I think this is a
common problem though.

Just Google the last line in the image

**Comment by laloalire** [comment]
just came back to thank you, now it is working pretty well!
The problem was USB 3.0 to boot MacOS, I needed a 2.0 USB 
Thank you for everything, now ill have to figure out how to fix sleep/imessage/facetime and ill be fully working.
![screen shot 2018-11-07 at 11 01 27 am](https://user-images.githubusercontent.com/18712668/48154061-90ebe180-e27c-11e8-9644-30d4e25c9738.png)

**Comment by Nihhaar** [comment]
Good to know :)
