### ISSUE TITLE
Low battery life?

### ISSUE THREAD

**Issue by mayankbudhwani** [Nihhaar/Hackintosh-Dell-7567#17]
I followed this guide and got 10.14 running on my laptop, but battery life is very low compared to Windows - about half.. Did I miss something? Essential files attached..
[Problem Reporting.zip](https://github.com/Nihhaar/Hackintosh-Dell-7567/files/2592661/Problem.Reporting.zip)

**Comment by Nihhaar** [comment]
Update VoodooI2C to latest version from its repo, the one I included has performance problems I think. If the battery life is still poor, check below.

Common causes for low battery life:
* Power Management: My files using HWP, check if it is working properly or not (just google it)
* Discrete GPU is not disabled: SSDT-Disable_DGPU.aml should work, check if nvidia card is present in system info

Use Intel Power Gadget to check cpu frequencies, see if they are going down when idle.

**Comment by mayankbudhwani** [comment]
OK I updated VoodooI2C.. I was noticing high CPU usage from hidd previously, maybe that was related to VoodooI2C(?)..hidd usage is somewhat lower now...
Can you tell me how to check if HWP is working properly? I googled it but couldn't find any clear guides..
dGPU is not showing up in System Information, it shows iGPU..
also CPU frequencies are going down as reported by Intel Power Gadget and cpu temps are almost on par with windows..
Also on an unrelated issue, I can't turn off bluetooth.. Turn off bluetooth is greyed out..
Can you tell me what kind of battery life you get? Do you get as much as Windows?

**Comment by Nihhaar** [comment]
* You can't turn off bluetooth, can be disabled in bios but it will be disabled in windows too
* Great, discrete GPU is disabled then
* Checking for HWP: Use AppleIntelInfo kext, https://www.insanelymac.com/forum/topic/304369-how-to-check-your-states-%E2%80%93-using-aicpminfo-msrdumper-or-appleintelinfo/

Yes, my battery life is similar to windows.

**Comment by mayankbudhwani** [comment]
I am attaching output from AppleIntelInfo, can you please check it?
[AppleIntelInfo.txt](https://github.com/Nihhaar/Hackintosh-Dell-7567/files/2592757/AppleIntelInfo.txt)

**Comment by Nihhaar** [comment]
Use latest AppleIntelInfo kext. You are using v1.4, use v2.9+. If HWP (aka SpeedShift) is enabled, these lines (similar, mine is an i7) will be in the log:
> IA32_PM_ENABLE...................(0x770) : 0x1 (HWP Supported and Enabled)
> 
> IA32_HWP_CAPABILITIES............(0x771) : 0x10B1C26
>
>  - Highest Performance.................. : 38
>  - Guaranteed Performance............... : 28
>  - Most Efficient Performance........... : 11
>  - Lowest Performance................... : 1

**Comment by mayankbudhwani** [comment]
Oops.. Sorry about that.. Here is the new file.. It does contain similar lines. Battery life is still lesser than Windows. Also I noticed that in Intel Power Gadget, frequency does not go below 1.3GHz, while in Windows it can drop  below 1GHz.. Why is that? Also Intel Power Gadget always shows GFX frequency as 0. why is that?
[AppleIntelInfo.txt](https://github.com/Nihhaar/Hackintosh-Dell-7567/files/2593048/AppleIntelInfo.txt)

**Comment by Nihhaar** [comment]
Your log is fine.
* macOS demands some base frequency to run the os (thats why minimum of 1.3GHz)
* No idea why GFX is 0Hz but it is same in my case also

**Comment by mayankbudhwani** [comment]
Hi.. Sorry to reply after so many days.. Can you tell me which DSDT patches you used? Coz I have SystemMemory address mismatch so I have to repatch DSDT.. I just used the original one (ACPI/origin) and everything works(surprisingly).. But did you use any DSDT patches?

**Comment by Nihhaar** [comment]
Hey,
The only patch I used for DSDT is GPIO pinning for VoodooI2C.
https://github.com/Nihhaar/Hackintosh-Dell-7567/commit/8ac65e5ea99c8ab5eee747ecbeeda2e410356648#diff-b6606d90bad6f012e39d84d334b3c960

**Comment by mayankbudhwani** [comment]
Well, my touchpad is working fine (most gestures are working), so is that patch required?
Also, on an unrelated note, the GFX frequency is shown in Intel Power Gadget if I enable Dell SMBIOS patch in Clover, but I don't know what the underlying implications of using that patch are.. Could you maybe give some insight as to what Dell SMBIOS patch does? I googled but found no good info..

**Comment by Nihhaar** [comment]
* No idea how trackpad is working without GPIO patch but I'll make sure to add this patch as an SSDT instead of DSDT so that the files work for all.
* Dell SMBIOS patch is created because of the issue with dell laptops truncating SMBIOS identifier. More info here: https://sourceforge.net/p/cloverefiboot/tickets/203/ & https://www.tonymacx86.com/threads/fix-for-dell-smbios-model-identifier-character-limit.213864/

I will add Dell SMBIOS patch next release if it is useful

**Comment by mayankbudhwani** [comment]
Hey. Does netflix work for you in safari?

**Comment by Nihhaar** [comment]
Sorry, couldn't get back to you. No, it doesn't work. Only works in chrome.

**Comment by Nihhaar** [comment]
Closing issue because I am archiving this repo.
