### ISSUE TITLE
Cannot Boot install_osx -V

### ISSUE THREAD

**Issue by AllenSarinana24** [Nihhaar/Hackintosh-Dell-7567#18]
Hello,

I cannot get my Dell Inspiron 7567 too boot into the Mac installation screen. -V gives me an error (will be attached) and without -v i get an apple logo with no progress on the bar. The error i receive with -V is Attempting system restart .... MACH Reboot. have followed all steps. 

Specs: 

Dell Inspiron 7000 7567
Processor: Intel i5-7300HQ 2.50 GHZ 7th Gen
16GD DDR4 RAM
Bios Version 1.70

Using a 64GB Sandisk 3.0 USB
![image](https://user-images.githubusercontent.com/41400607/49316668-df248700-f4ae-11e8-8455-6d74037188d8.png)

**Comment by Nihhaar** [comment]
Hi,
Can you attach your "clover" folder in the usb EFI? Also the photo shows kernel panic but I need photo at start of the trace (can be shot by slow-mo camera @ 120fps) for seeing which kext caused the panic.

**Comment by AllenSarinana24** [comment]
Hi,

hope those are good enough. Please let me know if you need better ones. Its kind of tough for the camera to focus when the code starts moving like crazy. haha.


![img_5161](https://user-images.githubusercontent.com/41400607/49319178-ccaf4b00-f4b8-11e8-8e53-7ed6809e5cef.PNG)
![img_5162](https://user-images.githubusercontent.com/41400607/49319179-ccaf4b00-f4b8-11e8-8c3c-a02ec44c4ff7.PNG)


[CLOVER.zip](https://github.com/Nihhaar/Hackintosh-Dell-7567/files/2635209/CLOVER.zip)

**Comment by AllenSarinana24** [comment]
This is the correct Clover file, sorry about the one i posted earlier. This is the clover folder where i drag and drop all of the files from the zip file you provided.

[CLOVER.zip](https://github.com/Nihhaar/Hackintosh-Dell-7567/files/2635248/CLOVER.zip)

**Comment by AllenSarinana24** [comment]
Here are some better ones that i took. 


![img_5186](https://user-images.githubusercontent.com/41400607/49319661-29136a00-f4bb-11e8-817e-912508ac455f.JPG)

![img_5188](https://user-images.githubusercontent.com/41400607/49319627-eea9cd00-f4ba-11e8-846e-ba8446b9aa88.JPG)
![img_5167](https://user-images.githubusercontent.com/41400607/49319628-ef426380-f4ba-11e8-8314-41f8bdc7d5d4.JPG)

**Comment by mayankbudhwani** [comment]
Well, I am relatively very new to Hackintosh so I don't know too much, but I did face similar issues when I was creating a USB. What did the trick for me was to use a small (8/16 gig) USB 2 disk having a single partition - also I noticed that Mac does not even show some of the partitions created by Windows. So you might try to erasing your USB completely - deleting all partition in Windows using a partition manager and recreating the USB on mac. Again, I don't know much about hackintosh, just posting from personal experience - so take this with a grain of salt. (also you can try using USB files from [this](https://www.tonymacx86.com/threads/guide-dell-inspiron-15-7567-and-similar-near-full-functionality.234988/) thread - although the ones here work fine, but it's worth a shot.

**Comment by Nihhaar** [comment]
Hi,
As @mayankbudhwani mentioned try USB2.0 if its possible and also, if you only have usb3.0, try placing the following SSDT file (extract it first) in your `USB/EFI/Clover/patched` folder and try again.
[SSDT-UIAC.aml.zip](https://github.com/Nihhaar/Hackintosh-Dell-7567/files/2635980/SSDT-UIAC.aml.zip)

Also,
* The error is happening still below the photos you posted and above the backtrace
* Update your BIOS to 1.8.1
* Make sure you set bios options as mentioned here https://www.tonymacx86.com/threads/guide-dell-inspiron-15-7567-and-similar-near-full-functionality.234988/:
>Make sure you are using UEFI under “Boot list option"
>Disable Legacy Option ROMs
>Change SATA operation to AHCI (it may be set to “RAID On” which it was for me)
>Make sure Secure Boot is disabled or else you won't be able to boot anything other than Windows >(basically...)
>Make sure VT for Direct I/O (VT-d) is disabled

**Comment by Nihhaar** [comment]
Closing issue because I am archiving this repo.
