### ISSUE TITLE
USB Wake from Sleep Immediately

### ISSUE THREAD

**Issue by Andrw0830** [Nihhaar/Hackintosh-Dell-7567#3]
Hello man, I just discovered your repo man and thanks so much. I just discovered that having an USB device plugged in and going to sleep causes my laptop to immediately resume from sleep. I don't recall having this issue before and heard it could be a couple things like applying a DSDT fix for instant wake but I could be wrong. Everything else is working good.

**Comment by Andrw0830** [comment]
I was able to fix it by using RehabMan's '[usb] USB3 _PRW 0x6D Skylake (instant wake)' just for your knowledge

**Comment by Nihhaar** [comment]
Thanks for the fix, will add it soon to the repo!
