### ISSUE TITLE
WhateverGreen Kext and Config for version 1.0.1

### ISSUE THREAD

**Issue by Lvieira21** [Nihhaar/Hackintosh-Dell-7567#4]
Hello!!

Thank you for putting all of this together! I have been trying to make my own hackintosh for weeks, and stumbling uppon this git was a salvation for me.

Anyways, I installed my system using your your 1.0 version released, as soon as I saw there was a 1.0.1, I started changing the new config.plist (With configured SMBIOS) for the one I previously had, and the new kexts that you updated for those I had previously installed. Unfortunately, as soon as I put your kexts, I got kernel panic. After getting to the HD through recovery and removing WhateverGreen, it came back to normal. Another thing was that, after getting a successfull boot, the trackpad was sloppy and not as accurate as before, and the gestures, seemed to be all crazy, after getting my backup confi.plist on its place again, the trackpad and the mouse started to behave normal again. 

Edit: Dell Inspiron Gaming 7567 - Intel i7 - 7700HQ; SSD 256gb; HDD 1tb; RAM 16gb; BIOS ver. 1.1.0

**Comment by Nihhaar** [comment]
Hey,
Thanks for your kind words!
Actually from 1.0 to 1.0.1, I also updated LiluFriend.kext, it might be the case that you didn't update it.

**Comment by Lvieira21** [comment]
Just tried a fresh install of the kexts from the 1.0.1 update, and I still had Kernel Panic from the WhateverGreen.
I did change the config file, It does seem to be working properly.
I'm on 10.13.3, do you think thats an update problem?
Should I update to 10.13.6?

**Comment by Nihhaar** [comment]
Weird, I think it is same as #5, try removing applealc and try. I don't think it is a os version problem

**Comment by Lvieira21** [comment]
Just did, Still KP.

Another thing, do you have a changelog on the tweaks that you made on the config.plist on version 1.0.1?
After I updated it, I dont really know if it was only the config, but I saw that there were some new DSDT patches, and kext patches>
Cause since I upgrade it to 1.0.1, my Hard Drive keeps spinning at a loud pace and I can hear the needle working all the time even on Iddle. 
When I tried to reboot it, stood here waiting for like, 10 minutes and it didnt shut down.
Another thing that I notice was that the HDD part of the notebook was really hot.

**Comment by Nihhaar** [comment]
Changelog (1.0 -> 1.0.1):
* Update LiluFriend plist
* Update config.plist

Actually diff of both 1.0 and 1.0.1 is
```
Only in /Users/nihhaar/Documents/Hackintosh-Dell7567-Nihhaar: .DS_Store
Binary files /Users/nihhaar/Documents/Hackintosh-Dell7567-Nihhaar/Clover Post-Install Files/.DS_Store and /Users/nihhaar/Documents/test/Clover Post-Install Files/.DS_Store differ
diff -r /Users/nihhaar/Documents/Hackintosh-Dell7567-Nihhaar/Clover Post-Install Files/:L:E Kexts/LiluFriend.kext/Contents/Info.plist /Users/nihhaar/Documents/test/Clover Post-Install Files/:L:E Kexts/LiluFriend.kext/Contents/Info.plist
69c69,71
<               <key>as.vit9696.WhateverGreen</key>
---
>               <key>as.lvs1974.IntelGraphicsFixup</key>
>               <string>1.0</string>
>               <key>as.vit9696.Shiki</key>
diff -r /Users/nihhaar/Documents/Hackintosh-Dell7567-Nihhaar/Clover Post-Install Files/config.plist /Users/nihhaar/Documents/test/Clover Post-Install Files/config.plist
224,227d223
<               <key>Hide</key>
<               <array>
<                       <string>Preboot</string>
<               </array>
Binary files /Users/nihhaar/Documents/Hackintosh-Dell7567-Nihhaar/Clover USB Files/.DS_Store and /Users/nihhaar/Documents/test/Clover USB Files/.DS_Store differ
Binary files /Users/nihhaar/Documents/Hackintosh-Dell7567-Nihhaar/Clover USB Files/kexts/.DS_Store and /Users/nihhaar/Documents/test/Clover USB Files/kexts/.DS_Store differ
```

**Comment by Nihhaar** [comment]
may be try 1.0.2? Just updated Lilu kext and AppleALC kext.

**Comment by Lvieira21** [comment]
Just tried the Lilu and AppleALC, they are working properly, but i didnt have the chance to put whatevergreen cause the Hackintosh is pretty unstable, my hard drive makes noises like it is being used at 100% rate. And the system is EXTREMELY slow. I couldnt even open the GeekBench to benchmark it.
How is your notebook handling hackintosh, and what about the general speed of it?

Here's my EFI folder, in any case: https://drive.google.com/open?id=19grYwu6WGhh1usPeGmjr34ZiX0WP4gnj

**Comment by Nihhaar** [comment]
My hackintosh is perfectly fine, though my hack is installed on the SSD. Your EFI is fine though, no idea why it is behaving weird. Did you try to mess with power options in settings of macOS and see any improvement?

**Comment by Lvieira21** [comment]
I'm going to try making a fresh install, I dont have much time right now, since I'm on my last semester of college, so, you can close this issue. Whenever I have more time, I'll come back to you.

Thanks very much for your help, Nihhaar! :)
