### ISSUE TITLE
AppleALC issue

### ISSUE THREAD

**Issue by Encore96** [Nihhaar/Hackintosh-Dell-7567#5]
Hi, Thanks for awesome guide. Everything is working, except AppleALC, idk why, but it causing a bootloop. I even can't catch a reason (but behavior seems like a KP) Version release is 1.0.1. MacOS X 10.13.5, Laptop config -
Dell 7567, NVMe Corsair Force MP500 SSD 240GB, 1TB 5400RPM WD HDD, i7-7700HQ.

**Comment by Nihhaar** [comment]
Hey,  
Can you post your EFI and /Library/Extensions/*? May be the case that Lilu or LiluFriend kext is not upto date.

Edit: Try installing AppleALC and then using `-liluoff` boot flag, see if your system has panic or not. Post the results.

**Comment by Encore96** [comment]
L/E contains all the recommended files except Whatevergreen. LiluFriend is configured w/o WhateverGreen. I tried files from your pack, and tried to update Lilu/AppleALC to latest version, but the last variant works fluently (w/o KP) only if files placed in EFI/Clover/Kexts. If it placed in L/E, sometimes it cause KP, but it could be overrided via Safe Mode and deleting the AppleALC.kext.
Your Lilu and AppleALC cause a bootloop :c 
If its important, my BIOS version is 1.7.0

Edit: Anyway, if i update AppleALC and Lilu to last version - it doesn't work. Even with new layout-11, or the old one (13)

**Comment by Nihhaar** [comment]
Oh okay, I'll try on my machine and will let you know (I'm little busy rn). Up until then, keep them in EFI/Clover/Other.

**Comment by Encore96** [comment]
Inform me please, when you try it. Thanks!)

**Comment by Nihhaar** [comment]
I actually tried now, no KP but no audio also. Try following kexts: 


[Archive.zip](https://github.com/Nihhaar/Hackintosh-Dell-7567/files/2320239/Archive.zip)

**Comment by Nihhaar** [comment]
Is this issue still there with latest release? or you managed to fix it?

**Comment by Encore96** [comment]
Still here, pal.

вт, 30 окт. 2018 г., 19:57 Nihhaar_RC <notifications@github.com>:

**Comment by Nihhaar** [comment]
Closing issue because I am archiving this repo.
