### ISSUE TITLE
Dell-7566 version

### ISSUE THREAD

**Issue by encku** [Nihhaar/Hackintosh-Dell-7567#6]
Hi All, 

I installed Mac OS X 10.13.6 with your bootloader but my usb's not working.

How can I achieve this issue please thanks for your help.

**Comment by Nihhaar** [comment]
7566 may have different USB configuration, try configuring SSDT-UIAC.aml to fit your needs. Probably some one did that already or refer to this guide:
https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/

**Comment by Nihhaar** [comment]
Closing issue because I am archiving this repo.
