### ISSUE TITLE
there is a way to use nvidia cart?

### ISSUE THREAD

**Issue by maxis7567** [Nihhaar/Hackintosh-Dell-7567#7]

**Comment by encku** [comment]
You can check **Is there a way to make Radeon or Nvidia graphics work in my dual-GPU laptop?**  in this guide

[https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/](url)

**Comment by Nihhaar** [comment]
No way to make nvidia work in laptops with optimus.
