### ISSUE TITLE
Headphone jack

### ISSUE THREAD

**Issue by maxis7567** [Nihhaar/Hackintosh-Dell-7567#9]
headphone jack on most headphones not working
when its working the sound is like this:
https://drive.google.com/open?id=1wzmUVJssZIwXReB0yqxSaY2BrDeiTwoq

**Comment by maxis7567** [comment]
No one has this problem
?

**Comment by Lvieira21** [comment]
No, mine worked perfectly, I was using high Sierra though.

**Comment by maxis7567** [comment]
i installed mojave , headphone works fine for two day and then the same problem
and in mojave after OS boot up for 10 sec its work 
i think one of my app its cause of this problem 
how can i find the app?
